name: Update cash reakout wf

on:
  schedule:
    # Runs every 15 minutes during Indian Market Hours (Mon-Fri)
    - cron: '*/15 3-10 * * 1-5'
  workflow_dispatch:

jobs:
  run-scanner:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yfinance gspread google-auth pytz

      - name: Run Market Scanner Script
        env:
          GCP_CREDENTIALS_JSON: ${{ secrets.GCP_CREDENTIALS_JSON }}
          SHEET_ID: ${{ secrets.SHEET_ID }}
        run: python update_sheet.py
